### ISSUE TITLE
Merge into ABRT

### ISSUE THREAD

**Issue by ernestask** [abrt/reportd#8]
For tracking purposes. Benefits include:
  * having one less daemon (even though it might be possible to make reportd non-persistent),
  * properly working authorization (ABRT will check if D-Bus caller is authorized, which breaks with e.g. Cockpit),
  * something else I’m forgetting.

**Comment by jfilak** [comment]
My 2 cents:
- reportd was supposed to run in a user session while abrtd runs in a system session with more privileges
- reportd should be started through D-Bus service activation on demand and should not be running otherwise

**Comment by ernestask** [comment]
> reportd was supposed to run in a user session while abrtd runs in a system session with more privileges

True. However, user sessions just do not work with Cockpit for e.g. root. polkit authorization, as I mentioned, breaks completely, since cockpit-bridge cannot do its job, so I had to place workarounds instead.

Lots of Cockpit being mentioned, because right now it’s the only (pending PR review and merge) consumer of the API reportd provides.

> reportd should be started through D-Bus service activation on demand and should not be running otherwise

It does remain persistent after activation, though. I’ve also run into ridiculous issues with the caching mechanism, like abrtd refusing to save updated reported_to element, because it does not allow problem directories to grow, unless you delete the element beforehand, at which point the new size almost does not matter. My biggest gripe was wasting precious disk space, but employing some systemd tricks to get it cleaned up after termination makes things better. It might go against the original design, though.

**Comment by xsuchy** [comment]
I think it is better to have this separate. Better to have several specialized tools rather than one swiss army knife, which has no real use.

**Comment by ernestask** [comment]
How is this a “specialized tool”?

**Comment by xsuchy** [comment]
Like a standalone.

@ernestask do you still argue for this? If yes, then feel free to reopen. I am not going to fight on this one. :)
